travis:
  secure:
    BINSTAR_TOKEN: gXk57+V0uYYX8H0ii67lo99VYgzuG18CDH3LUelnCTKxmwx7eFmNbTyAr4Z4rVjrW3ByFR3PJl9QrEhxrTw7/qlzemjTjDD4NCq5EZpm/Kg7tkMYMn1CTEpHiFZlneq6vnKCHkmwNYKUbSVO6ZW3RNIZTGCA3fYEzMrnRmmIFFrc7+xlcRFEa+CbwyOMrJiQ6VWdhRhlSZWBqu5S4iu2TTn1mwKB5EpHPfGzrkYqjYB123cMgHl+aNlAJHotMSCQxVbV938HPTKvwwOQzpKp9aRWQUmEi93AeauJLVg4Jc0bPFQ097eqwTOJg6j9BZVa9BCPmiqK4ZKbcvT782Xw9zkTgz90Qb7aEAywD49fiu726kUDfll3SXOoQDhfe5892RQEeXq6k6eqo3mxcjOWz3tmYDMn1heD/4/7PfNNmYPLTfrNYM7CSQd1nMhfMQkXdKajYWq/eyZaThXoLdhcdvL3uk0nizOwW8oDlhh4jxcySahb5eYxdeJ1G19Zm4teCPNE0VePHYvKTP12gSSxbi5qq8ayEb9y9ZaY9FwKTrCkFUmxGHqUqndJazh3DVwyvi+1i59d7Bftk6EzgXKh1GgcL6cFO8jjcyJ9yWUcreeq6YswPFx8QN6z06A0oMa8B2nrA72VVPogONmD2NNmJ8/PyPk5UnUGwN63ic3tO7o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
